# Generated by Django 4.0.5 on 2022-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='go_bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bot Name ')),
                ('level_of_risk', models.CharField(choices=[('Super High Risk', 'Super High Risk'), ('Very Risk', 'Very Risk'), ('High Risk', 'High Risk'), ('Moderate Risk', 'Moderate Risk'), ('Low Risk', 'Low Risk')], max_length=150, verbose_name='Risk Level')),
                ('trading_pairs', models.CharField(choices=[('US30 NAS100', 'US30 NAS100'), ('US30 NAS100 SPX500', 'US30, NAS100,SPX500'), ('GOLD', 'GOLD'), ('FX', 'FX'), ('INDICES GOLD FX', 'INDICES, GOLD, FX')], max_length=150, verbose_name='Trading Pairs')),
                ('company', models.CharField(max_length=150, verbose_name='Broker Company')),
                ('server', models.CharField(max_length=150, verbose_name='Server Name')),
                ('login', models.IntegerField(verbose_name='Account Number')),
                ('master_password', models.CharField(max_length=200, verbose_name='Master Password')),
                ('investor_password', models.CharField(max_length=200, verbose_name='Investor Password')),
            ],
        ),
    ]
