# Generated by Django 4.0.5 on 2022-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_gold_bot_level_of_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx_bot',
            name='level_of_risk',
            field=models.CharField(choices=[('Super High Risk', 'Super High Risk'), ('Very Risk', 'Very Risk'), ('High Risk', 'High Risk'), ('High', 'High'), ('Moderate Risk', 'Moderate Risk'), ('Low Risk', 'Low Risk')], max_length=150, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='indices_bot',
            name='level_of_risk',
            field=models.CharField(choices=[('Super High Risk', 'Super High Risk'), ('Very Risk', 'Very Risk'), ('High Risk', 'High Risk'), ('High', 'High'), ('Moderate Risk', 'Moderate Risk'), ('Low Risk', 'Low Risk')], max_length=150, verbose_name='Risk Level'),
        ),
    ]
