# Generated by Django 4.0.5 on 2022-07-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_indices_bots_delete_indices_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='indices_bots',
            new_name='indices_bot',
        ),
    ]
