# Generated by Django 4.0.5 on 2022-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_rename_indices_bots_indices_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx_bot',
            name='capital_required',
            field=models.FloatField(default=100.0, verbose_name='Capital Field'),
        ),
        migrations.AddField(
            model_name='fx_bot',
            name='pricing',
            field=models.FloatField(default=100.0, verbose_name='pricingpricing'),
        ),
        migrations.AddField(
            model_name='gold_bot',
            name='capital_required',
            field=models.FloatField(default=100.0, verbose_name='Capital Field'),
        ),
        migrations.AddField(
            model_name='gold_bot',
            name='pricing',
            field=models.FloatField(default=100.0, verbose_name='pricingpricing'),
        ),
        migrations.AddField(
            model_name='indices_bot',
            name='capital_required',
            field=models.FloatField(default=100.0, verbose_name='Capital Field'),
        ),
        migrations.AddField(
            model_name='indices_bot',
            name='pricing',
            field=models.FloatField(default=100.0, verbose_name='pricingpricing'),
        ),
    ]
