# Generated by Django 4.0.5 on 2022-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_fx_bot_capital_required_fx_bot_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx_bot',
            name='capital_required',
            field=models.FloatField(default=0.0, verbose_name='Capital Field'),
        ),
        migrations.AlterField(
            model_name='fx_bot',
            name='pricing',
            field=models.FloatField(default=0.0, verbose_name='pricingpricing'),
        ),
        migrations.AlterField(
            model_name='gold_bot',
            name='capital_required',
            field=models.FloatField(default=0.0, verbose_name='Capital Field'),
        ),
        migrations.AlterField(
            model_name='gold_bot',
            name='pricing',
            field=models.FloatField(default=0.0, verbose_name='pricingpricing'),
        ),
        migrations.AlterField(
            model_name='indices_bot',
            name='capital_required',
            field=models.FloatField(default=0.0, verbose_name='Capital Field'),
        ),
        migrations.AlterField(
            model_name='indices_bot',
            name='pricing',
            field=models.FloatField(default=0.0, verbose_name='pricingpricing'),
        ),
    ]
