# Generated by Django 4.0.5 on 2022-07-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_alter_fx_bot_capital_required_alter_fx_bot_pricing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bot Name ')),
                ('capital_required', models.FloatField(default=0.0, verbose_name='Capital Field')),
                ('pricing', models.FloatField(default=0.0, verbose_name='pricingpricing')),
                ('level_of_risk', models.CharField(choices=[('Super High Risk', 'Super High Risk'), ('Very Risk', 'Very Risk'), ('High Risk', 'High Risk'), ('High', 'High'), ('Moderate Risk', 'Moderate Risk'), ('Low Risk', 'Low Risk')], max_length=150, verbose_name='Risk Level')),
                ('company', models.CharField(max_length=150, verbose_name='Broker Company')),
                ('server', models.CharField(max_length=150, verbose_name='Server Name')),
                ('login', models.IntegerField(verbose_name='Account Number')),
                ('master_password', models.CharField(max_length=200, verbose_name='Master Password')),
                ('investor_password', models.CharField(max_length=200, verbose_name='Investor Password')),
            ],
        ),
    ]
