# Generated by Django 4.0.5 on 2022-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_crypto_bot_instruments_fx_bot_instruments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_bot',
            name='choose_platform',
            field=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5')], default='MT4', max_length=50, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='fx_bot',
            name='choose_platform',
            field=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5')], default='MT4', max_length=50, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='gold_bot',
            name='choose_platform',
            field=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5')], default='MT4', max_length=50, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='indices_bot',
            name='choose_platform',
            field=models.CharField(choices=[('MT4', 'MT4'), ('MT5', 'MT5')], default='MT4', max_length=50, verbose_name='Platform'),
        ),
    ]
