# Generated by Django 4.0.5 on 2022-07-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_crypto_bot_non_paid_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_bot',
            name='non_paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Non-Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='crypto_bot',
            name='paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='fx_bot',
            name='non_paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Non-Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='fx_bot',
            name='paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='gold_bot',
            name='non_paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Non-Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='gold_bot',
            name='paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='indices_bot',
            name='non_paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Non-Paid Subscribers'),
        ),
        migrations.AlterField(
            model_name='indices_bot',
            name='paid_subscribers',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Paid Subscribers'),
        ),
    ]
