# Generated by Django 4.0.5 on 2022-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_add_client_trading_account_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_client_trading_account',
            name='account_number',
            field=models.CharField(max_length=300, unique=True, verbose_name='Account_Number'),
        ),
    ]
