# Generated by Django 4.0.5 on 2022-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_add_client_trading_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_client_trading_account',
            name='status',
            field=models.CharField(choices=[('Deactivate', 'Deactivate'), ('Active', 'Active')], default='Deactivate', max_length=120, verbose_name='Status'),
        ),
    ]
