# Generated by Django 4.0.5 on 2022-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_add_client_trading_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_client_trading_account',
            name='broker_name',
            field=models.CharField(default='', max_length=100, verbose_name='Broker Name'),
        ),
        migrations.AlterField(
            model_name='add_client_trading_account',
            name='account_password',
            field=models.CharField(max_length=300, verbose_name='Password'),
        ),
    ]
