# Generated by Django 4.0.5 on 2022-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_client_trading_account_broker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_client_trading_account',
            name='created_by',
            field=models.CharField(default='', max_length=156, verbose_name='Owner'),
        ),
    ]
