# Generated by Django 4.0.5 on 2022-07-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_add_client_trading_account_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_client_trading_account',
            name='created_by',
        ),
    ]
