# Generated by Django 4.0.5 on 2022-07-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_add_client_trading_account_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_client_trading_account',
            name='created_by',
            field=models.EmailField(default='email@company.com', max_length=156, verbose_name='Owner'),
        ),
    ]
